---
title: Open Savannah
timezone: UTC
markdown: kramdown
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: yall@opensavannah.org  
description: 'Part of the Code for America Brigade network, we are a volunteer group
  of developers, designers, data geeks, and citizen activists who use creative technology
  to solve civic and social problems.'
baseurl: ''
url: http://codeforboston.org
hackpad_url: https://codeforboston.hackpad.com/
twitter_url: https://twitter.com/codeforboston
github_url: https://github.com/codeforboston
meetup_url: https://meetup.com/Code-For-Boston
blog_url: https://medium.com/@CodeForBoston
events_url: http://cal.codeforboston.org
slack_url: http://slack.codeforboston.org
